about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

from posts import views


handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    # дополнительно к стандартному фреймворку авторизаций
    # добавлено представление для регистрации
    path('404/', views.page_not_found, name='404'),
    path('500/', views.server_error, name='500'),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include('about.urls', namespace='about')),
    path("", include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)

templates/include/avatar_text_block.html
<div class="col-md-3 mb-3 mt-1">
  <div class="card">
    <div class="card-body">
      <div class="h2"> Автор:<br> {{ author.get_full_name }}</div>
        <div class="h3 text-muted"> Пользователь: @{{ author.username }} </div>
    </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <div class="h6 text-muted"> Подписчиков: {{ author.following.all.count }} <br /> Подписан: {{ author.follower.all.count }} </div>
        </li>
        <li class="list-group-item">
          <div class="h6 text-muted"> Количество записей: {{ number_of_posts }} </div>
        </li>

        {% if user.is_authenticated %}
        <li class="list-group-item">
          {% if following %}
          <a class="btn btn-lg btn-light" 
                  href="{% url 'profile_unfollow' profile.username %}" role="button"> 
                  Отписаться 
          </a> 
          {% else %}
          <a class="btn btn-lg btn-primary" 
                  href="{% url 'profile_follow' profile.username %}" role="button">
          Подписаться 
          </a>
          {% endif %}
      </li>
      {% endif %}

      </ul>
  </div>
</div>

templates/include/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <form method="post" action="{% url 'add_comment' post.author.username post.id  %}">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

<!-- Комментарии -->
{% for item in comments %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %} 

templates/include/footer.html
<!-- <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {{ year }}, все права защищены.</p>
</footer> -->

<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
      <a href="{% url 'about:author' %}">Об авторе</a>
      <a href="{% url 'about:tech' %}">Технологии</a>
  </p>
  <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {{ year }}, все права защищены.</p>
</footer> 

templates/include/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="/follow">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}

templates/include/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span>tube</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
      Пользователь: {{ request.user }}.
      <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a>
      <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
      <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav> 

templates/include/paginator.html
{% if page.has_other_pages %}
  <nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
      {% if page.number == i %}
        <li class="page-item active">
          <span class="page-link">{{ i }}
            <span class="sr-only">(текущая)</span>
          </span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
  </nav>
{% endif %} 

templates/include/picture.html
{% load thumbnail %}
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}">
{% endthumbnail %}
    

templates/include/post_block.html
<div class="card mb-3 mt-1 shadow-sm">
  {% include "include/picture.html" %}
  <div class="card-body">
    <p class="card-text"> <a href="{% url 'profile' post.author.username %}"><strong class="d-block text-gray-dark">@{{ post.author.username }}</strong></a> {{ post.text }} </p>
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group "> <a class="btn btn-sm text-muted" href="{% url 'add_comment' post.author.username post.id   %}" role="button">Добавить комментарий</a>
        {% if user.username == request.user.username %}
          <a class="btn btn-sm text-muted" href="{% url 'post_edit' post.author.username post.id  %}" role="button">Редактировать</a>
        {%endif%}
      </div>                
      <small class="text-muted">Дата публикации: {{ post.pub_date|date:"d M Y" }}</small> </div>
  </div>
</div>

templates/include/post_item.html
{% load thumbnail %}
<div class="card mb-3 mt-1 shadow-sm">

  <!-- Отображение картинки -->
  
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img" src="{{ im.url }}" />
  {% endthumbnail %}
  <!-- Отображение текста поста -->
  <div class="card-body">
    <p class="card-text">
      <!-- Ссылка на автора через @ -->
      <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}">
        <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
      </a>
      {{ post.text|linebreaksbr }}
    </p>

    <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
    {% if post.group %}
    <a class="card-link muted" href="{% url 'group_posts' post.group.slug %}">
      <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
    </a>
    {% endif %}

    <!-- Отображение ссылки на комментарии -->
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        {% if post.comments.exists %}
        <div>
          Комментариев: {{ post.comments.count }}
        </div>
        {% endif %}
        <a class="btn btn-sm btn-primary" href="{% url 'post' post.author.username post.id %}" role="button">
          Добавить комментарий
        </a>

        <!-- Ссылка на редактирование поста для автора -->
        {% if user == post.author %}
        <a class="btn btn-sm btn-info" href="{% url 'post_edit' post.author.username post.id %}" role="button">
          Редактировать
        </a>
        {% endif %}
      </div>

      <!-- Дата публикации поста -->
      <small class="text-muted">{{ post.pub_date }}</small>
    </div>
  </div>
</div> 